[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:queue]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3
user=www-data
autostart=true
autorestart=true

[program:scheduler]
command=sh -c "while [ true ]; do php /var/www/html/artisan schedule:run --no-interaction & sleep 60; done"
user=www-data
autostart=true
autorestart=true
